export const keywords = [
  "OneTAC",
  "Tourism, Art, and Culture (TAC)",
  "Decentralized Digital Infrastructure",
  "Indian Cultural Experiences",
  "Local Artisans Empowerment",
  "Community-driven Tourism",
  "Open Transactional Networks",
  "Cultural Heritage Preservation",
  "Sustainable Travel",
  "Digital Public Infrastructure",
  "Beckn Protocol",
  "Culkey Foundation",
  "EkStep Foundation",
  "Tourism Innovation",
  "Cultural Diversity Promotion",
  "Authentic Indian Experiences",
  "Local Business Growth in TAC",
  "Open Network for TAC",
  "Digital Empowerment of Artisans",
  "Collaborative Cultural Platforms",
];
