import { Plus_Jakarta_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

const argaka = localFont({
  src: "./fonts/ArgakaFashion-Regular.ttf",
  variable: "--font-argaka-fashion",
});

const telma = localFont({
  src: "./fonts/Telma.ttf",
  variable: "--font-telma",
});

export const metadata = {
  title: "OneTAC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${argaka.variable} ${telma.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}